/*
Auto-generated by C4D to R3F Converter
Model: brickBalloon.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial, SplineElement } from '../../SceneComponents'
import type { PaletteName } from '../../GameSettings'
import modelUrl from './brickBalloon.glb?url'

type ColorSlot = 'colorOne' | 'colorTwo'

type BrickBalloonProps = ThreeElements['group'] & {
  animation?: string | null
  fadeDuration?: number
  colorOne?: PaletteName
  colorTwo?: PaletteName
}

export function BrickBalloon({ animation = null, fadeDuration = 0.3, colorOne = 'five', colorTwo = 'three', ...props }: BrickBalloonProps) {
  const group = useRef<THREE.Group | null>(null)
  const { nodes, animations } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh>; animations: THREE.AnimationClip[] }
  const { actions } = useAnimations(animations, group)

  // Crossfade mellan animationer
  // animation={null} = rest position, animation="moving" = spela
  useEffect(() => {
    Object.values(actions).forEach((a) => a?.fadeOut(fadeDuration))
    if (animation && actions[animation]) {
      actions[animation].reset().fadeIn(fadeDuration).play()
    }
  }, [animation, fadeDuration, actions])

  // Tillgängliga animationer: "moving"


  const colors: Record<ColorSlot, PaletteName> = {
    colorOne,
    colorTwo,
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name={"BALLOON"} position={[0, 0.6, 0]}>
        <group name={"BRICK"} position={[0, -0.3, 0]}>
          {/* Rectangle_1 */}
          <SplineElement
            points={[[0, 0.025, -0.025], [0, 0.025, -0.0217], [0, 0.025, -0.0183], [0, 0.025, -0.015], [0, 0.025, -0.0117], [0, 0.025, -0.0083], [0, 0.025, -0.005], [0, 0.025, -0.0017], [0, 0.025, 0.0017], [0, 0.025, 0.005], [0, 0.025, 0.0083], [0, 0.025, 0.0117], [0, 0.025, 0.015], [0, 0.025, 0.0183], [0, 0.025, 0.0217], [0, 0.025, 0.025], [0, 0.0217, 0.025], [0, 0.0183, 0.025], [0, 0.015, 0.025], [0, 0.0117, 0.025], [0, 0.0083, 0.025], [0, 0.005, 0.025], [0, 0.0017, 0.025], [0, -0.0017, 0.025], [0, -0.005, 0.025], [0, -0.0083, 0.025], [0, -0.0117, 0.025], [0, -0.015, 0.025], [0, -0.0183, 0.025], [0, -0.0217, 0.025], [0, -0.025, 0.025], [0, -0.025, 0.0217], [0, -0.025, 0.0183], [0, -0.025, 0.015], [0, -0.025, 0.0117], [0, -0.025, 0.0083], [0, -0.025, 0.005], [0, -0.025, 0.0017], [0, -0.025, -0.0017], [0, -0.025, -0.005], [0, -0.025, -0.0083], [0, -0.025, -0.0117], [0, -0.025, -0.015], [0, -0.025, -0.0183], [0, -0.025, -0.0217], [0, -0.025, -0.025], [0, -0.0217, -0.025], [0, -0.0183, -0.025], [0, -0.015, -0.025], [0, -0.0117, -0.025], [0, -0.0083, -0.025], [0, -0.005, -0.025], [0, -0.0017, -0.025], [0, 0.0017, -0.025], [0, 0.005, -0.025], [0, 0.0083, -0.025], [0, 0.0117, -0.025], [0, 0.015, -0.025], [0, 0.0183, -0.025], [0, 0.0217, -0.025]]}
            closed={true}
            tension={0.5}
            curveType="catmullrom"
          />
          {/* Rectangle */}
          <SplineElement
            points={[[0.05, 0.025, 0], [0.0433, 0.025, 0], [0.0367, 0.025, 0], [0.03, 0.025, 0], [0.0233, 0.025, 0], [0.0167, 0.025, 0], [0.01, 0.025, 0], [0.0033, 0.025, 0], [-0.0033, 0.025, 0], [-0.01, 0.025, 0], [-0.0167, 0.025, 0], [-0.0233, 0.025, 0], [-0.03, 0.025, 0], [-0.0367, 0.025, 0], [-0.0433, 0.025, 0], [-0.05, 0.025, 0], [-0.05, 0.0217, 0], [-0.05, 0.0183, 0], [-0.05, 0.015, 0], [-0.05, 0.0117, 0], [-0.05, 0.0083, 0], [-0.05, 0.005, 0], [-0.05, 0.0017, 0], [-0.05, -0.0017, 0], [-0.05, -0.005, 0], [-0.05, -0.0083, 0], [-0.05, -0.0117, 0], [-0.05, -0.015, 0], [-0.05, -0.0183, 0], [-0.05, -0.0217, 0], [-0.05, -0.025, 0], [-0.0433, -0.025, 0], [-0.0367, -0.025, 0], [-0.03, -0.025, 0], [-0.0233, -0.025, 0], [-0.0167, -0.025, 0], [-0.01, -0.025, 0], [-0.0033, -0.025, 0], [0.0033, -0.025, 0], [0.01, -0.025, 0], [0.0167, -0.025, 0], [0.0233, -0.025, 0], [0.03, -0.025, 0], [0.0367, -0.025, 0], [0.0433, -0.025, 0], [0.05, -0.025, 0], [0.05, -0.0217, 0], [0.05, -0.0183, 0], [0.05, -0.015, 0], [0.05, -0.0117, 0], [0.05, -0.0083, 0], [0.05, -0.005, 0], [0.05, -0.0017, 0], [0.05, 0.0017, 0], [0.05, 0.005, 0], [0.05, 0.0083, 0], [0.05, 0.0117, 0], [0.05, 0.015, 0], [0.05, 0.0183, 0], [0.05, 0.0217, 0]]}
            closed={true}
            tension={0.5}
            curveType="catmullrom"
          />
          <C4DMesh name={nodes['Cube_colorFive'].name} geometry={nodes['Cube_colorFive'].geometry} castShadow receiveShadow>
            <C4DMaterial color={colors.colorOne} />
          </C4DMesh>
        </group>
        <C4DMesh name={nodes['Sphere_colorThree_singleTone'].name} geometry={nodes['Sphere_colorThree_singleTone'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.colorTwo} />
        </C4DMesh>
        <C4DMesh name={nodes['Cone_colorThree_singleTone'].name} geometry={nodes['Cone_colorThree_singleTone'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.colorTwo} />
        </C4DMesh>
        {/* Line */}
        <SplineElement
          points={[[0, 0, 0], [0, 0.0125, 0], [0, 0.025, 0], [0, 0.0375, 0], [0, 0.05, 0], [0, 0.0625, 0], [0, 0.075, 0], [0, 0.0875, 0], [0, 0.1, 0], [0, 0.1125, 0], [0, 0.125, 0], [0, 0.1375, 0], [0, 0.15, 0], [0, 0.1625, 0], [0, 0.175, 0], [0, 0.1875, 0], [0, 0.2, 0], [0, 0.2125, 0], [0, 0.225, 0], [0, 0.2375, 0], [0, 0.25, 0], [0, 0.2625, 0], [0, 0.275, 0], [0, 0.2875, 0], [0, 0.3, 0]]}
          closed={false}
          tension={0.5}
          curveType="catmullrom"
          rotation={[180, 0, 0]}
        />
      </group>

    </group>
  )
}

useGLTF.preload(modelUrl)