/*
Auto-generated by C4D to R3F Converter
Model: GIFTBALLOON.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial, SplineElement } from '@/scene/SceneComponents'
import type { MaterialColorIndex } from '@/settings/GameSettings'
import modelUrl from './GIFTBALLOON.glb?url'

type MaterialColorSlot = 'materialColor0' | 'materialColor1'
type MaterialHiddenSlot = 'materialHidden0'

type GIFTBALLOONProps = ThreeElements['group'] & {
  materialColor0?: MaterialColorIndex
  materialColor1?: MaterialColorIndex
  materialHidden0?: boolean
}

export function GIFTBALLOON({ materialColor0 = 1, materialColor1 = 2, materialHidden0 = false, ...props }: GIFTBALLOONProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }

  const materialColors: Record<MaterialColorSlot, MaterialColorIndex> = {
    materialColor0,
    materialColor1,
  }

  const materialHiddens: Record<MaterialHiddenSlot, boolean> = {
    materialHidden0,
  }

  return (
    <group {...props} dispose={null}>
      <group name={"GIFTBALLOON"}>
        <C4DMesh name={nodes['BALOON_color1_singleTone'].name} geometry={nodes['BALOON_color1_singleTone'].geometry} castShadow receiveShadow position={[0, -0.19, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor0} singleTone />
        </C4DMesh>
        <group name={"ROPES"} position={[0, -0.19, 0]}>
          {/* ROPES_1 */}
          <SplineElement
            points={[[-0.0307,0.0237,0],[-0.0294,0.0196,0],[-0.0281,0.0155,0],[-0.0269,0.0114,0],[-0.0256,0.0073,0],[-0.0243,0.0032,0],[-0.023,-0.0009,0],[-0.0217,-0.0051,0],[-0.0205,-0.0092,0],[-0.0192,-0.0133,0],[-0.0179,-0.0174,0],[-0.0166,-0.0215,0],[-0.0153,-0.0256,0],[-0.0141,-0.0297,0],[-0.0128,-0.0339,0],[-0.0115,-0.038,0],[-0.0102,-0.0421,0],[-0.009,-0.0462,0],[-0.0077,-0.0503,0],[-0.0064,-0.0544,0],[-0.0051,-0.0585,0],[-0.0038,-0.0627,0],[-0.0026,-0.0668,0],[-0.0013,-0.0709,0],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_2 */}
          <SplineElement
            points={[[0.0307,0.0237,0],[0.0294,0.0196,0],[0.0281,0.0155,0],[0.0269,0.0114,0],[0.0256,0.0073,0],[0.0243,0.0032,0],[0.023,-0.0009,0],[0.0217,-0.0051,0],[0.0205,-0.0092,0],[0.0192,-0.0133,0],[0.0179,-0.0174,0],[0.0166,-0.0215,0],[0.0153,-0.0256,0],[0.0141,-0.0297,0],[0.0128,-0.0339,0],[0.0115,-0.038,0],[0.0102,-0.0421,0],[0.009,-0.0462,0],[0.0077,-0.0503,0],[0.0064,-0.0544,0],[0.0051,-0.0585,0],[0.0038,-0.0627,0],[0.0026,-0.0668,0],[0.0013,-0.0709,0],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_3 */}
          <SplineElement
            points={[[0,0.0237,-0.0307],[0,0.0196,-0.0294],[0,0.0155,-0.0281],[0,0.0114,-0.0269],[0,0.0073,-0.0256],[0,0.0032,-0.0243],[0,-0.0009,-0.023],[0,-0.0051,-0.0217],[0,-0.0092,-0.0205],[0,-0.0133,-0.0192],[0,-0.0174,-0.0179],[0,-0.0215,-0.0166],[0,-0.0256,-0.0153],[0,-0.0297,-0.0141],[0,-0.0339,-0.0128],[0,-0.038,-0.0115],[0,-0.0421,-0.0102],[0,-0.0462,-0.009],[0,-0.0503,-0.0077],[0,-0.0544,-0.0064],[0,-0.0585,-0.0051],[0,-0.0627,-0.0038],[0,-0.0668,-0.0026],[0,-0.0709,-0.0013],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_4 */}
          <SplineElement
            points={[[0,0.0237,0.0307],[0,0.0196,0.0294],[0,0.0155,0.0281],[0,0.0114,0.0269],[0,0.0073,0.0256],[0,0.0032,0.0243],[0,-0.0009,0.023],[0,-0.0051,0.0217],[0,-0.0092,0.0205],[0,-0.0133,0.0192],[0,-0.0174,0.0179],[0,-0.0215,0.0166],[0,-0.0256,0.0153],[0,-0.0297,0.0141],[0,-0.0339,0.0128],[0,-0.038,0.0115],[0,-0.0421,0.0102],[0,-0.0462,0.009],[0,-0.0503,0.0077],[0,-0.0544,0.0064],[0,-0.0585,0.0051],[0,-0.0627,0.0038],[0,-0.0668,0.0026],[0,-0.0709,0.0013],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_5 */}
          <SplineElement
            points={[[0,-0.21,0],[0,-0.2044,0],[0,-0.1988,0],[0,-0.1931,0],[0,-0.1875,0],[0,-0.1819,0],[0,-0.1762,0],[0,-0.1706,0],[0,-0.165,0],[0,-0.1594,0],[0,-0.1538,0],[0,-0.1481,0],[0,-0.1425,0],[0,-0.1369,0],[0,-0.1312,0],[0,-0.1256,0],[0,-0.12,0],[0,-0.1144,0],[0,-0.1088,0],[0,-0.1031,0],[0,-0.0975,0],[0,-0.0919,0],[0,-0.0862,0],[0,-0.0806,0],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
        </group>
        <C4DMesh name={nodes['box_wrap_x_right_color1'].name} geometry={nodes['box_wrap_x_right_color1'].geometry} castShadow receiveShadow position={[0, -0.4, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor0} />
        </C4DMesh>
        <C4DMesh name={nodes['box_wrap_z_right_color1'].name} geometry={nodes['box_wrap_z_right_color1'].geometry} castShadow receiveShadow position={[0, -0.4, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor0} />
        </C4DMesh>
        <C4DMesh name={nodes['box_top_right_color2'].name} geometry={nodes['box_top_right_color2'].geometry} castShadow receiveShadow position={[0, -0.4, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor1} />
        </C4DMesh>
        <C4DMesh name={nodes['box_top_left_color2'].name} geometry={nodes['box_top_left_color2'].geometry} castShadow receiveShadow position={[0, -0.4, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor1} />
        </C4DMesh>
        <C4DMesh name={nodes['box_sides_color2'].name} geometry={nodes['box_sides_color2'].geometry} castShadow receiveShadow position={[0, -0.4, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor1} />
        </C4DMesh>
        <C4DMesh name={nodes['box_bottom_color2'].name} geometry={nodes['box_bottom_color2'].geometry} castShadow receiveShadow position={[0, -0.4, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor1} />
        </C4DMesh>
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)