/*
Auto-generated by C4D to R3F Converter
Model: laddertest.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { CuboidCollider } from '@react-three/rapier'
import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial, GameRigidBody } from '../../SceneComponents'
import type { GamePhysicsBodyType } from '../../SceneComponents'
import type { MaterialColorIndex } from '../../GameSettings'
import modelUrl from './laddertest.glb?url'

type GeneratedRigidBodySettings = {
  type: GamePhysicsBodyType
  mass?: number
  friction?: number
  lockRotations?: boolean
  sensor?: boolean
}

type LaddertestProps = ThreeElements['group'] & {
  materialColor0?: MaterialColorIndex
  rigidBodyOne?: Partial<GeneratedRigidBodySettings>
}

export function Laddertest({ materialColor0 = 0, rigidBodyOne, ...props }: LaddertestProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }
  const materialColors: Record<'materialColor0', MaterialColorIndex> = {
    materialColor0,
  }

  const rigidBodies: Record<'rigidBodyOne', GeneratedRigidBodySettings> = {
    rigidBodyOne: { type: 'dynamic', ...(rigidBodyOne ?? {}) },
  }

  const getRigidBodyProps = (slot: 'rigidBodyOne'): GeneratedRigidBodySettings => {
    const body = rigidBodies[slot]
    return {
      type: body.type,
      ...(body.mass !== undefined ? { mass: body.mass } : {}),
      ...(body.friction !== undefined ? { friction: body.friction } : {}),
      ...(body.lockRotations ? { lockRotations: true } : {}),
      ...(body.sensor ? { sensor: true } : {}),
    }
  }

  return (
    <group {...props} dispose={null}>
      <GameRigidBody {...getRigidBodyProps('rigidBodyOne')} colliders={false}>
        <CuboidCollider args={[0.075, 0.345, 0.015]} position={[0, 0.345, 0]} />
        <C4DMesh name={nodes['HORIZONTALS'].name} geometry={nodes['HORIZONTALS'].geometry} castShadow receiveShadow>
          <C4DMaterial color={materialColors.materialColor0} />
        </C4DMesh>
      </GameRigidBody>
    </group>
  )
}

useGLTF.preload(modelUrl)
