/*
Auto-generated by C4D to R3F Converter
Model: stair.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, ConvexHullCollider } from '@react-three/rapier'
import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial } from '../../SceneComponents'
import type { PaletteName } from '../../GameSettings'
import modelUrl from './stair.glb?url'

type GeneratedRigidBodySettings = {
  type: 'dynamic' | 'fixed' | 'kinematicPosition'
  mass?: number
  friction?: number
  lockRotations?: boolean
  sensor?: boolean
}

type StairProps = ThreeElements['group'] & {
  colorOne?: PaletteName
  rigidBodyOne?: Partial<GeneratedRigidBodySettings>
}

export function Stair({ colorOne = 'three', rigidBodyOne, ...props }: StairProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }
  const colors: Record<'colorOne', PaletteName> = {
    colorOne,
  }

  const rigidBodies: Record<'rigidBodyOne', GeneratedRigidBodySettings> = {
    rigidBodyOne: { type: 'dynamic', ...(rigidBodyOne ?? {}) },
  }

  const getRigidBodyProps = (slot: 'rigidBodyOne'): GeneratedRigidBodySettings => {
    const body = rigidBodies[slot]
    return {
      type: body.type,
      ...(body.mass !== undefined ? { mass: body.mass } : {}),
      ...(body.friction !== undefined ? { friction: body.friction } : {}),
      ...(body.lockRotations ? { lockRotations: true } : {}),
      ...(body.sensor ? { sensor: true } : {}),
    }
  }

  return (
    <group {...props} dispose={null}>
      <RigidBody {...getRigidBodyProps('rigidBodyOne')} colliders={false}>
        <ConvexHullCollider args={[nodes['STAIRS_collider'].geometry.attributes.position.array]} />
        <C4DMesh name={nodes['STAIRS'].name} geometry={nodes['STAIRS'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.colorOne} />
        </C4DMesh>
        <C4DMesh name={nodes['STAIRS_top'].name} geometry={nodes['STAIRS_top'].geometry} castShadow receiveShadow>
          <C4DMaterial color={colors.colorOne} />
        </C4DMesh>
      </RigidBody>
    </group>
  )
}

useGLTF.preload(modelUrl)
