/*
Auto-generated by C4D to R3F Converter
Model: testgeo.gltf
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, ConvexHullCollider } from '@react-three/rapier'
import { C4DMesh, C4DMaterial } from '../../SceneComponents'
import modelUrl from './testgeo.gltf?url'

export function Testgeo(props) {
  const { nodes, materials } = useGLTF(modelUrl)
  const colors = {
    default: 'default',
  }

  return (
    <group {...props} dispose={null}>
      <C4DMesh geometry={nodes['Pelvis'].geometry} castShadow receiveShadow position={[0, 0.9, 0]}>
        <C4DMaterial color={colors.default} />
        <C4DMesh geometry={nodes['LeftThigh'].geometry} castShadow receiveShadow position={[0.0773, -0.0533, 0]} rotation={[-0.0698, 0, 0.0524]}>
          <C4DMaterial color={colors.default} />
          <C4DMesh geometry={nodes['LeftShin'].geometry} castShadow receiveShadow position={[0, -0.3813, 0]} rotation={[0.1571, 0, -0.0524]}>
            <C4DMaterial color={colors.default} />
            <C4DMesh geometry={nodes['LeftFoot'].geometry} castShadow receiveShadow position={[0.004, -0.428, 0]} rotation={[-0.0873, 0, 0]}>
              <C4DMaterial color={colors.default} />
              <C4DMesh geometry={nodes['LeftJoint'].geometry} castShadow receiveShadow>
                <C4DMaterial color={colors.default} />
              </C4DMesh>
            </C4DMesh>
            <C4DMesh geometry={nodes['LeftJoint_1'].geometry} castShadow receiveShadow>
              <C4DMaterial color={colors.default} />
            </C4DMesh>
          </C4DMesh>
          <C4DMesh geometry={nodes['LeftJoint_2'].geometry} castShadow receiveShadow>
            <C4DMaterial color={colors.default} />
          </C4DMesh>
        </C4DMesh>
        <C4DMesh geometry={nodes['Right_Thigh'].geometry} castShadow receiveShadow position={[-0.0773, -0.0533, 0]} rotation={[-0.0698, 0, -0.0524]}>
          <C4DMaterial color={colors.default} />
          <C4DMesh geometry={nodes['Right_Shin'].geometry} castShadow receiveShadow position={[0, -0.3813, 0]} rotation={[0.1571, 0, 0.0524]}>
            <C4DMaterial color={colors.default} />
            <C4DMesh geometry={nodes['Right_Foot'].geometry} castShadow receiveShadow position={[-0.004, -0.428, 0]} rotation={[-0.0873, 0, 0]}>
              <C4DMaterial color={colors.default} />
              <C4DMesh geometry={nodes['Right_Joint'].geometry} castShadow receiveShadow>
                <C4DMaterial color={colors.default} />
              </C4DMesh>
            </C4DMesh>
            <C4DMesh geometry={nodes['Right_Joint_1'].geometry} castShadow receiveShadow>
              <C4DMaterial color={colors.default} />
            </C4DMesh>
          </C4DMesh>
          <C4DMesh geometry={nodes['Right_Joint_2'].geometry} castShadow receiveShadow>
            <C4DMaterial color={colors.default} />
          </C4DMesh>
        </C4DMesh>
        <C4DMesh geometry={nodes['Upper_Body'].geometry} castShadow receiveShadow position={[0, 0.2267, 0]}>
          <C4DMaterial color={colors.default} />
          <C4DMesh geometry={nodes['LeftUpper_Arm'].geometry} castShadow receiveShadow position={[0.1453, 0.232, 0]} rotation={[0, 0.1745, 0]}>
            <C4DMaterial color={colors.default} />
            <C4DMesh geometry={nodes['LeftLower_Arm'].geometry} castShadow receiveShadow position={[0.3307, 0, 0]} rotation={[0, -0.1745, 0]}>
              <C4DMaterial color={colors.default} />
              <C4DMesh geometry={nodes['LeftHand'].geometry} castShadow receiveShadow position={[0.2907, 0, 0]}>
                <C4DMaterial color={colors.default} />
                <C4DMesh geometry={nodes['LeftJoint_3'].geometry} castShadow receiveShadow>
                  <C4DMaterial color={colors.default} />
                </C4DMesh>
              </C4DMesh>
              <C4DMesh geometry={nodes['LeftJoint_4'].geometry} castShadow receiveShadow>
                <C4DMaterial color={colors.default} />
              </C4DMesh>
            </C4DMesh>
            <C4DMesh geometry={nodes['LeftJoint_5'].geometry} castShadow receiveShadow>
              <C4DMaterial color={colors.default} />
            </C4DMesh>
          </C4DMesh>
          <C4DMesh geometry={nodes['Right_Upper_Arm'].geometry} castShadow receiveShadow position={[-0.1453, 0.232, 0]} rotation={[0, -0.1745, 0]}>
            <C4DMaterial color={colors.default} />
            <C4DMesh geometry={nodes['Right_Lower_Arm'].geometry} castShadow receiveShadow position={[-0.3307, 0, 0]} rotation={[0, 0.1745, 0]}>
              <C4DMaterial color={colors.default} />
              <C4DMesh geometry={nodes['Right_Hand'].geometry} castShadow receiveShadow position={[-0.2907, 0, 0]}>
                <C4DMaterial color={colors.default} />
                <C4DMesh geometry={nodes['Right_Joint_3'].geometry} castShadow receiveShadow>
                  <C4DMaterial color={colors.default} />
                </C4DMesh>
              </C4DMesh>
              <C4DMesh geometry={nodes['Right_Joint_4'].geometry} castShadow receiveShadow>
                <C4DMaterial color={colors.default} />
              </C4DMesh>
            </C4DMesh>
            <C4DMesh geometry={nodes['Right_Joint_5'].geometry} castShadow receiveShadow>
              <C4DMaterial color={colors.default} />
            </C4DMesh>
          </C4DMesh>
          <C4DMesh geometry={nodes['Head'].geometry} castShadow receiveShadow position={[0, 0.3733, 0]}>
            <C4DMaterial color={colors.default} />
            <C4DMesh geometry={nodes['Neck'].geometry} castShadow receiveShadow>
              <C4DMaterial color={colors.default} />
            </C4DMesh>
          </C4DMesh>
          <C4DMesh geometry={nodes['Joint'].geometry} castShadow receiveShadow>
            <C4DMaterial color={colors.default} />
          </C4DMesh>
        </C4DMesh>
      </C4DMesh>
    </group>
  )
}

useGLTF.preload(modelUrl)