/*
Auto-generated by C4D to R3F Converter
Model: TIMEBALLOON.glb
*/

import * as THREE from 'three'
import { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

import type { ThreeElements } from '@react-three/fiber'
import { C4DMesh, C4DMaterial, SplineElement } from '@/scene/SceneComponents'
import type { MaterialColorIndex } from '@/settings/GameSettings'
import modelUrl from './TIMEBALLOON.glb?url'

type MaterialColorSlot = 'materialColor0' | 'materialColor1'
type MaterialHiddenSlot = 'materialHidden0'

type TIMEBALLOONProps = ThreeElements['group'] & {
  materialColor0?: MaterialColorIndex
  materialColor1?: MaterialColorIndex
  materialHidden0?: boolean
}

export function TIMEBALLOON({ materialColor0 = 1, materialColor1 = 2, materialHidden0 = false, ...props }: TIMEBALLOONProps) {
  const { nodes } = useGLTF(modelUrl) as unknown as { nodes: Record<string, THREE.Mesh> }

  const materialColors: Record<MaterialColorSlot, MaterialColorIndex> = {
    materialColor0,
    materialColor1,
  }

  const materialHiddens: Record<MaterialHiddenSlot, boolean> = {
    materialHidden0,
  }

  return (
    <group {...props} dispose={null}>
      <group name={"TIMEBALOON"}>
        <C4DMesh name={nodes['BALOON_color1_singleTone'].name} geometry={nodes['BALOON_color1_singleTone'].geometry} castShadow receiveShadow position={[0, -0.19, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor0} singleTone />
        </C4DMesh>
        <group name={"CLOCK_button"} position={[0, -0.45, 0]} rotation={[0, 0, 0.7854]}>
          <C4DMesh name={nodes['CLOCK_button_top_color2_singleTone'].name} geometry={nodes['CLOCK_button_top_color2_singleTone'].geometry} castShadow receiveShadow position={[0, 0.13, 0]} visible={!materialHiddens.materialHidden0}>
            <C4DMaterial color={materialColors.materialColor1} singleTone />
          </C4DMesh>
          <C4DMesh name={nodes['CLOCK_button_stem_color2_singleTone'].name} geometry={nodes['CLOCK_button_stem_color2_singleTone'].geometry} castShadow receiveShadow position={[0, 0.11, 0]} visible={!materialHiddens.materialHidden0}>
            <C4DMaterial color={materialColors.materialColor1} singleTone />
          </C4DMesh>
        </group>
        <group name={"CLOCK_button_2"} position={[0, -0.45, 0]} rotation={[0, 0, -0.7854]}>
          <C4DMesh name={nodes['CLOCK_button_top_color2_singleTone_2'].name} geometry={nodes['CLOCK_button_top_color2_singleTone_2'].geometry} castShadow receiveShadow position={[0, 0.13, 0]} visible={!materialHiddens.materialHidden0}>
            <C4DMaterial color={materialColors.materialColor1} singleTone />
          </C4DMesh>
          <C4DMesh name={nodes['CLOCK_button_stem_color2_singleTone_2'].name} geometry={nodes['CLOCK_button_stem_color2_singleTone_2'].geometry} castShadow receiveShadow position={[0, 0.11, 0]} visible={!materialHiddens.materialHidden0}>
            <C4DMaterial color={materialColors.materialColor1} singleTone />
          </C4DMesh>
        </group>
        <group name={"ROPES"} position={[0, -0.19, 0]}>
          {/* ROPES_1 */}
          <SplineElement
            points={[[-0.0307,0.0237,0],[-0.0294,0.0196,0],[-0.0281,0.0155,0],[-0.0269,0.0114,0],[-0.0256,0.0073,0],[-0.0243,0.0032,0],[-0.023,-0.0009,0],[-0.0217,-0.0051,0],[-0.0205,-0.0092,0],[-0.0192,-0.0133,0],[-0.0179,-0.0174,0],[-0.0166,-0.0215,0],[-0.0153,-0.0256,0],[-0.0141,-0.0297,0],[-0.0128,-0.0339,0],[-0.0115,-0.038,0],[-0.0102,-0.0421,0],[-0.009,-0.0462,0],[-0.0077,-0.0503,0],[-0.0064,-0.0544,0],[-0.0051,-0.0585,0],[-0.0038,-0.0627,0],[-0.0026,-0.0668,0],[-0.0013,-0.0709,0],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_2 */}
          <SplineElement
            points={[[0.0307,0.0237,0],[0.0294,0.0196,0],[0.0281,0.0155,0],[0.0269,0.0114,0],[0.0256,0.0073,0],[0.0243,0.0032,0],[0.023,-0.0009,0],[0.0217,-0.0051,0],[0.0205,-0.0092,0],[0.0192,-0.0133,0],[0.0179,-0.0174,0],[0.0166,-0.0215,0],[0.0153,-0.0256,0],[0.0141,-0.0297,0],[0.0128,-0.0339,0],[0.0115,-0.038,0],[0.0102,-0.0421,0],[0.009,-0.0462,0],[0.0077,-0.0503,0],[0.0064,-0.0544,0],[0.0051,-0.0585,0],[0.0038,-0.0627,0],[0.0026,-0.0668,0],[0.0013,-0.0709,0],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_3 */}
          <SplineElement
            points={[[0,0.0237,-0.0307],[0,0.0196,-0.0294],[0,0.0155,-0.0281],[0,0.0114,-0.0269],[0,0.0073,-0.0256],[0,0.0032,-0.0243],[0,-0.0009,-0.023],[0,-0.0051,-0.0217],[0,-0.0092,-0.0205],[0,-0.0133,-0.0192],[0,-0.0174,-0.0179],[0,-0.0215,-0.0166],[0,-0.0256,-0.0153],[0,-0.0297,-0.0141],[0,-0.0339,-0.0128],[0,-0.038,-0.0115],[0,-0.0421,-0.0102],[0,-0.0462,-0.009],[0,-0.0503,-0.0077],[0,-0.0544,-0.0064],[0,-0.0585,-0.0051],[0,-0.0627,-0.0038],[0,-0.0668,-0.0026],[0,-0.0709,-0.0013],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_4 */}
          <SplineElement
            points={[[0,0.0237,0.0307],[0,0.0196,0.0294],[0,0.0155,0.0281],[0,0.0114,0.0269],[0,0.0073,0.0256],[0,0.0032,0.0243],[0,-0.0009,0.023],[0,-0.0051,0.0217],[0,-0.0092,0.0205],[0,-0.0133,0.0192],[0,-0.0174,0.0179],[0,-0.0215,0.0166],[0,-0.0256,0.0153],[0,-0.0297,0.0141],[0,-0.0339,0.0128],[0,-0.038,0.0115],[0,-0.0421,0.0102],[0,-0.0462,0.009],[0,-0.0503,0.0077],[0,-0.0544,0.0064],[0,-0.0585,0.0051],[0,-0.0627,0.0038],[0,-0.0668,0.0026],[0,-0.0709,0.0013],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
          {/* ROPES_5 */}
          <SplineElement
            points={[[0,-0.124,0],[0,-0.1219,0],[0,-0.1199,0],[0,-0.1178,0],[0,-0.1158,0],[0,-0.1138,0],[0,-0.1117,0],[0,-0.1097,0],[0,-0.1076,0],[0,-0.1056,0],[0,-0.1036,0],[0,-0.1015,0],[0,-0.0995,0],[0,-0.0974,0],[0,-0.0954,0],[0,-0.0934,0],[0,-0.0913,0],[0,-0.0893,0],[0,-0.0872,0],[0,-0.0852,0],[0,-0.0832,0],[0,-0.0811,0],[0,-0.0791,0],[0,-0.077,0],[0,-0.075,0]]}
            closed={false}
            tension={0.5}
            visible={!materialHiddens.materialHidden0}
            curveType="catmullrom"
          />
        </group>
        <C4DMesh name={nodes['CLOCK_holder_color2_singleTone'].name} geometry={nodes['CLOCK_holder_color2_singleTone'].geometry} castShadow receiveShadow position={[0, -0.36, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor1} singleTone />
        </C4DMesh>
        <C4DMesh name={nodes['CLOCK_body_color2_singleTone'].name} geometry={nodes['CLOCK_body_color2_singleTone'].geometry} castShadow receiveShadow position={[0, -0.45, 0]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor1} singleTone />
        </C4DMesh>
        <C4DMesh name={nodes['CLOCKPINS_color1_singleTone'].name} geometry={nodes['CLOCKPINS_color1_singleTone'].geometry} castShadow receiveShadow position={[0, -0.45, 0.07]} rotation={[0, 0, -2.1642]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor0} singleTone />
        </C4DMesh>
        <C4DMesh name={nodes['CLOCKPINS_color1_singleTone_2'].name} geometry={nodes['CLOCKPINS_color1_singleTone_2'].geometry} castShadow receiveShadow position={[0, -0.45, 0.055]} visible={!materialHiddens.materialHidden0}>
          <C4DMaterial color={materialColors.materialColor0} singleTone />
        </C4DMesh>
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)